---
galaxy_info:
  author: Rhys Campbell
  description: A simple role to configure a Cassandra Repository for RedHat and Debian based systems.
  platforms:
    - name: RedHat
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all

  galaxy_tags:
    - cassandra
    - database
